/*  daqdrv.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/atomic.h>
#include <linux/types.h>
#include <linux/fs.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/cdev.h>
#include <linux/sysfs.h>
#include <linux/kobject.h>
#include <linux/spinlock.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

#include "kfifo-iomod.h"

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("daqdrv - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "daqdrv"

#define FPGA_BUF_LEN 4096
#define FIFO_BUF_LEN FPGA_BUF_LEN * 8

#define ADC_RUN_BIT 0
#define DAC_RUN_BIT 1

#define OVERWRITE_BIT 0

#define REG_SET_BIT(reg, bit) reg = reg | (1u << bit)
#define REG_UNSET_BIT(reg, bit) reg = reg & ~(1u << bit)
#define REG_GET_BIT(reg, bit) ((reg & (1u << bit)) >> bit)

static int daqdrv_open(struct inode *, struct file *);
static int daqdrv_release(struct inode *, struct file *);
static ssize_t daqdrv_read(struct file *, char __user *, size_t, loff_t *);
static ssize_t daqdrv_write(struct file *, const char __user *, size_t, loff_t *);

static int major; /* major number assigned to our device driver */
static int num_of_dev = 1;
enum {
	CDEV_NOT_USED,
	CDEV_EXCLUSIVE_OPEN
};
static atomic_t already_open = ATOMIC_INIT(CDEV_NOT_USED);

static struct class *cls;

static struct file_operations chardev_fops = {
	.read = daqdrv_read,
	.write = daqdrv_write,
	.open = daqdrv_open,
	.release = daqdrv_release,
};

struct daqdrv_local {
	int irq;
	struct cdev chardev;
	unsigned long buffer_mem_start;
	unsigned long buffer_mem_end;
	unsigned long ctrl_mem_start;
	unsigned long ctrl_mem_end;
	unsigned long stat_mem_start;
	unsigned long stat_mem_end;
	void __iomem *buffer_base_addr;
	void __iomem *ctrl_base_addr;
	void __iomem *stat_base_addr;
	struct kfifo_iomod fifo;
	bool overflowing;
	bool prev_overflowing;
	struct kobject *module_object;
	u32 fpga_buffer
};

static bool dataReady;

DEFINE_SPINLOCK(sl_dataReady);

static ssize_t dataReady_show(struct kobject *kobj, struct kobj_attribute *attr, char *buf)
{
	if (dataReady) {
		buf[0] = '1';
		buf[1] = 0;
	} else {
		buf[0] = '0';
		buf[1] = 0;
	}
	return 1;
}

static struct kobj_attribute dataReady_attribute = __ATTR_RO(dataReady);

static irqreturn_t daqdrv_irq(int irq, void *lp)
{
	struct daqdrv_local *lpp = (struct daqdrv_local *)lp;
	u32 availible = kfifo_iomod_avail(&(lpp->fifo));

	lpp->prev_overflowing = lpp->overflowing;

	if (availible < 4*FPGA_BUF_LEN) {
		lpp->overflowing = true;
	} else {
		lpp->overflowing = false;
	}

	if (lpp->overflowing == true && lpp->prev_overflowing == false) {
		printk("Started overflowwing! Dropping data, no space in fifo.\n");
	}

	if (lpp->overflowing == false && lpp->prev_overflowing == true) {
		printk("Stopped overflowing.\n");
	}

	if (lpp->overflowing == false) {
		kfifo_iomod_in(&(lpp->fifo), lpp->buffer_base_addr, 4*FPGA_BUF_LEN);
		u32 stat_reg = ioread32(lp->stat_base_addr);

		if (REG_GET_BIT(stat_reg, OVERWRITE_BIT)) {
			printk("FPGA buffer might be overwritten, IRQ was too slow!");
		}

		unsigned long flags;
		spin_lock_irqsave(&sl_dataReady, flags);
		dataReady = true;
		spin_unlock_irqrestore(&sl_dataReady, flags);
	}
	return IRQ_HANDLED;
}

static int daqdrv_open(struct inode *inode, struct file *file)
{
	if (atomic_cmpxchg(&already_open, CDEV_NOT_USED, CDEV_EXCLUSIVE_OPEN))
		return -EBUSY;

	try_module_get(THIS_MODULE);

	struct daqdrv_local *lp = container_of(inode->i_cdev, struct daqdrv_local, chardev);
	if (lp == NULL) {
		printk("drv data is null\n");
		return -ENOTRECOVERABLE;
	}
	
	u32 ctrl_reg = ioread32(lp->ctrl_base_addr);
	REG_SET_BIT(ctrl_reg, ADC_RUN_BIT);
	REG_SET_BIT(ctrl_reg, DAC_RUN_BIT);
	iowrite32(ctrl_reg, lp->ctrl_base_addr);
	return 0;
}
static int daqdrv_release(struct inode *inode, struct file *file)
{
	struct daqdrv_local *lp = container_of(inode->i_cdev, struct daqdrv_local, chardev);
	if (lp == NULL) {
		printk("drv data is null");
		return -ENOTRECOVERABLE;
	}
	
	u32 ctrl_reg = ioread32(lp->ctrl_base_addr);
	REG_UNSET_BIT(ctrl_reg, ADC_RUN_BIT)
	REG_UNSET_BIT(ctrl_reg, DAC_RUN_BIT)
	iowrite32(ctrl_reg, lp->ctrl_base_addr);

	unsigned long flags;
	spin_lock_irqsave(&sl_dataReady, flags);
	dataReady = false;
	spin_unlock_irqrestore(&sl_dataReady, flags);

	kfifo_iomod_reset_out(&(lp->fifo));
	lp->overflowing = false;
	lp->prev_overflowing = false;

	atomic_set(&already_open, CDEV_NOT_USED);
	module_put(THIS_MODULE);
	return 0;
}
static ssize_t daqdrv_read(struct file *filp, char __user *buffer, size_t length, loff_t *offset)
{
	if (filp->f_inode == NULL) {
		printk("can't find inode\n");
		return 0;
	}

	if (filp->f_inode->i_cdev == NULL) {
		printk("can't find chardev\n");
		return 0;
	}

	struct daqdrv_local *lp = container_of(filp->f_inode->i_cdev, struct daqdrv_local, chardev);
	if (lp == NULL) {
		printk("drv data is null\n");
		return 0;
	}

	size_t availible_data = (size_t)kfifo_iomod_len(&(lp->fifo));
	size_t min_length = min(length, availible_data);
	size_t aligned_len = min_length - (min_length % 4);

	if (aligned_len == 0) {
		return -EAGAIN;
	}

	size_t actual_len = 0;
	int ret_copy = kfifo_iomod_to_user(&(lp->fifo), buffer, aligned_len, &actual_len);

	if (ret_copy) {
		printk("EFAULT when copying to userspace!");
		return ret_copy;
	}

	if (actual_len == availible_data) {
		unsigned long flags;
		spin_lock_irqsave(&sl_dataReady, flags);
		dataReady = false;
		spin_unlock_irqrestore(&sl_dataReady, flags);
	}

	return actual_len;
}

static ssize_t daqdrv_write(struct file *filp, const char __user *buff, size_t len, loff_t *off)
{
	pr_alert("Sorry, this operation is not supported.\n");
	return -EINVAL;
}

static int daqdrv_probe(struct platform_device *pdev)
{
	//struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem_buff; /* IO mem resources */
	struct resource *r_mem_ctrl; /* IO mem resources */
	struct resource *r_mem_stat; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct daqdrv_local *lp = NULL;
	dev_t dvt;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */

	// Get iospace for buffer
	r_mem_buff = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem_buff) {
		dev_err(dev, "invalid address for buffer\n");
		return -ENODEV;
	}

	// Get iospace for ctrl
	r_mem_ctrl = platform_get_resource(pdev, IORESOURCE_MEM, 1);
	if (!r_mem_ctrl) {
		dev_err(dev, "invalid address for ctrl\n");
		return -ENODEV;
	}

	// Get iospace for stat
	r_mem_stat = platform_get_resource(pdev, IORESOURCE_MEM, 2);
	if (!r_mem_stat) {
		dev_err(dev, "invalid address for stat\n");
		return -ENODEV;
	}

	// init and allocate daqdrv_local structure
	lp = (struct daqdrv_local *) kmalloc(sizeof(struct daqdrv_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate daqdrv device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->buffer_mem_start = r_mem_buff->start;
	lp->buffer_mem_end = r_mem_buff->end;
	lp->ctrl_mem_start = r_mem_ctrl->start;
	lp->ctrl_mem_end = r_mem_ctrl->end;
	lp->stat_mem_start = r_mem_stat->start;
	lp->stat_mem_end = r_mem_stat->end;
	dataReady = false;

	spin_lock_init(&sl_dataReady);

	// request memory region for buffer
	if (!request_mem_region(lp->buffer_mem_start,
				lp->buffer_mem_end - lp->buffer_mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->buffer_mem_start);
		rc = -EBUSY;
		goto error1;
	}

	// request memory region for ctrl
	if (!request_mem_region(lp->ctrl_mem_start,
				lp->ctrl_mem_end - lp->ctrl_mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->ctrl_mem_start);
		rc = -EBUSY;
		goto error2;
	}

	// request memory region for stat
	if (!request_mem_region(lp->stat_mem_start,
				lp->stat_mem_end - lp->stat_mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->stat_mem_start);
		rc = -EBUSY;
		goto error3;
	}

	// remap buffer
	lp->buffer_base_addr = ioremap(lp->buffer_mem_start, lp->buffer_mem_end - lp->buffer_mem_start + 1);
	if (!lp->buffer_base_addr) {
		dev_err(dev, "daqdrv: Could not allocate iomem for buffer\n");
		rc = -EIO;
		goto error4;
	}

	// remap ctrl
	lp->ctrl_base_addr = ioremap(lp->ctrl_mem_start, lp->ctrl_mem_end - lp->ctrl_mem_start + 1);
	if (!lp->ctrl_base_addr) {
		dev_err(dev, "daqdrv: Could not allocate iomem for ctrl\n");
		rc = -EIO;
		goto error5;
	}

	// remap stat
	lp->stat_base_addr = ioremap(lp->stat_mem_start, lp->stat_mem_end - lp->stat_mem_start + 1);
	if (!lp->stat_base_addr) {
		dev_err(dev, "daqdrv: Could not allocate iomem for stat\n");
		rc = -EIO;
		goto error6;
	}

	// allocate character device 
	int ret_alloc_chardev = alloc_chrdev_region(&dvt, 0, num_of_dev, DRIVER_NAME);
	if (ret_alloc_chardev) {
		dev_err(dev, "Allocating char device failed with %d\n", ret_alloc_chardev);
		rc = ret_alloc_chardev;
		goto error7;
	}

	// register character device
	major = MAJOR(dvt);
	cdev_init(&(lp->chardev), &chardev_fops);
	int ret_cdev_add = cdev_add(&(lp->chardev), dvt, num_of_dev);
	if (ret_cdev_add) {
		dev_err(dev, "Registering char device failed with %d\n", ret_cdev_add);
		rc = ret_cdev_add;
		goto error8;
	}

	// Create device file
	dev_info(dev, "I was assigned major number %d.\n", major);
	cls = class_create(DRIVER_NAME);
	device_create(cls, NULL, dvt, NULL, DRIVER_NAME);
	dev_info(dev, "Device created on /dev/%s\n", DRIVER_NAME);

	// allocate fifo
	int ret_fifo_alloc = kfifo_iomod_alloc(&(lp->fifo), FIFO_BUF_LEN*4, GFP_KERNEL);
	if (ret_fifo_alloc) {
		dev_err(dev, "Allocating fifo failed with %d\n", ret_fifo_alloc);
		rc = ret_fifo_alloc;
		goto error9;
	}

	// create sysfs files
	lp->module_object = kobject_create_and_add(DRIVER_NAME, kernel_kobj);
	if (!lp->module_object) {
		dev_err(dev, "Kobject creation failed.\n");
		rc = -ENOMEM;
		goto error10;
	}

	int ret_sysfs_create_file = sysfs_create_file(lp->module_object, &dataReady_attribute.attr);
	if (ret_sysfs_create_file) {
		dev_err(dev, "Sysfs file creation failed with %d.\n", ret_sysfs_create_file);
		rc = ret_sysfs_create_file;
		goto error11;
	}

	// get interrupt
	int n_irq = platform_get_irq_optional(pdev, 0);
	if (n_irq < 0) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "daqdrv buffer at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->buffer_mem_start,
			(unsigned int __force)lp->buffer_base_addr);
		dev_info(dev, "daqdrv ctrl at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->ctrl_mem_start,
			(unsigned int __force)lp->ctrl_base_addr);
		dev_info(dev, "daqdrv stat at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->stat_mem_start,
			(unsigned int __force)lp->stat_base_addr);
		return 0;
	}
	lp->irq = n_irq;

	// register interrupt
	rc = request_irq(lp->irq, &daqdrv_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "daqdrv: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error12;
	}

	dev_info(dev,"daqdrv buffer at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->buffer_mem_start,
		(unsigned int __force)lp->buffer_base_addr,
		lp->irq);
	dev_info(dev,"daqdrv ctrl at 0x%08x mapped to 0x%08x",
		(unsigned int __force)lp->ctrl_mem_start,
		(unsigned int __force)lp->ctrl_base_addr);
	dev_info(dev,"daqdrv stat at 0x%08x mapped to 0x%08x",
		(unsigned int __force)lp->stat_mem_start,
		(unsigned int __force)lp->stat_base_addr);
	return 0;
error12:
	free_irq(lp->irq, lp);
error11:
	kobject_put(lp->module_object);
error10:
	kfifo_iomod_free(&(lp->fifo));
error9:
	device_destroy(cls, dvt);
	class_destroy(cls);
	cdev_del(&(lp->chardev));
error8:
	unregister_chrdev_region(dvt, num_of_dev);
error7:
	iounmap(lp->stat_base_addr);
error6:
	iounmap(lp->ctrl_base_addr);
error5:
	iounmap(lp->buffer_base_addr);
error4:
	release_mem_region(lp->stat_mem_start, lp->stat_mem_end - lp->stat_mem_start + 1);
error3:
	release_mem_region(lp->ctrl_mem_start, lp->ctrl_mem_end - lp->ctrl_mem_start + 1);
error2:
	release_mem_region(lp->buffer_mem_start, lp->buffer_mem_end - lp->buffer_mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int daqdrv_remove(struct platform_device *pdev)
{
	dev_t dvt = MKDEV(major, 0);
	struct device *dev = &pdev->dev;
	struct daqdrv_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	kobject_put(lp->module_object);
	kfifo_iomod_free(&(lp->fifo));

	device_destroy(cls, dvt);
	class_destroy(cls);
	cdev_del(&(lp->chardev));
	unregister_chrdev_region(dvt, num_of_dev);

	iounmap(lp->stat_base_addr);
	iounmap(lp->ctrl_base_addr);
	iounmap(lp->buffer_base_addr);
	release_mem_region(lp->stat_mem_start, lp->stat_mem_end - lp->stat_mem_start + 1);
	release_mem_region(lp->ctrl_mem_start, lp->ctrl_mem_end - lp->ctrl_mem_start + 1);
	release_mem_region(lp->buffer_mem_start, lp->buffer_mem_end - lp->buffer_mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id daqdrv_of_match[] = {
	{ .compatible = "stasbucik,daqdrv", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, daqdrv_of_match);
#else
# define daqdrv_of_match
#endif


static struct platform_driver daqdrv_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= daqdrv_of_match,
	},
	.probe		= daqdrv_probe,
	.remove		= daqdrv_remove,
};

static int __init daqdrv_init(void)
{
	printk("<1>DAQ driver loaded.\n");
	return platform_driver_register(&daqdrv_driver);
}


static void __exit daqdrv_exit(void)
{
	platform_driver_unregister(&daqdrv_driver);
	printk(KERN_ALERT "DAQ driver exited.\n");
}

module_init(daqdrv_init);
module_exit(daqdrv_exit);
