/*  daqdrv.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/atomic.h>
#include <linux/types.h>
#include <linux/fs.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("daqdrv - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "daqdrv"

#define BUF_LEN 4096

static int major; /* major number assigned to our device driver */
enum {
	CDEV_NOT_USED,
	CDEV_EXCLUSIVE_OPEN
};
static atomic_t already_open = ATOMIC_INIT(CDEV_NOT_USED);
static u32 samples[BUF_LEN];

static struct class *cls;

// static struct file_operations chardev_fops = {
// 	.read = daqdrv_read,
// 	.open = daqdrv_open,
// 	.release = daqdrv_release,
// };

struct daqdrv_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

static irqreturn_t daqdrv_irq(int irq, void *lp)
{
	// for (int i = 0; i < BUF_LEN; i++)
	// {
		
	// }
	// ioread32_rep(((struct daqdrv_local *)lp)->base_addr, samples, 8);
	memcpy_fromio(samples, ((struct daqdrv_local *)lp)->base_addr, 4*BUF_LEN);
	return IRQ_HANDLED;
}

// static int device_open(struct inode *inode, struct file *file)
// {
// 	if (atomic_cmpxchg(&already_open, CDEV_NOT_USED, CDEV_EXCLUSIVE_OPEN))
// 		return -EBUSY;

// 	try_module_get(THIS_MODULE);
// 	return 0;
// }
// static int device_release(struct inode *inode, struct file *file)
// {
// 	atomic_set(&already_open, CDEV_NOT_USED);
// 	module_put(THIS_MODULE);
// 	return 0;
// }
// static ssize_t device_read(struct file *filp, char __user *buffer, size_t length, loff_t *offset)
// {

// }

static int daqdrv_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct daqdrv_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct daqdrv_local *) kmalloc(sizeof(struct daqdrv_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate daqdrv device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "daqdrv: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	// major = register_chrdev(0, DRIVER_NAME, &chardev_fops);
	// if (major < 0) {
	// 	pr_alert("Registering char device failed with %d\n", major);
	// 	return major;
	// }
	// pr_info("I was assigned major number %d.\n", major);
	// cls = class_create(DRIVER_NAME);
	// device_create(cls, NULL, MKDEV(major, 0), NULL, DRIVER_NAME);
	// pr_info("Device created on /dev/%s\n", DRIVER_NAME);

	/* Get IRQ for the device */
	// r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	// if (!r_irq) {
	// 	dev_info(dev, "no IRQ found\n");
	// 	dev_info(dev, "daqdrv at 0x%08x mapped to 0x%08x\n",
	// 		(unsigned int __force)lp->mem_start,
	// 		(unsigned int __force)lp->base_addr);
	// 	return 0;
	// }
	// lp->irq = r_irq->start;

	int n_irq = platform_get_irq_optional(pdev, 0);
	if (n_irq < 0) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "daqdrv at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = n_irq;



	rc = request_irq(lp->irq, &daqdrv_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "daqdrv: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"daqdrv at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int daqdrv_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct daqdrv_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);

	// device_destroy(cls, MKDEV(major, 0));
	// class_destroy(cls);
	// unregister_chrdev(major, DRIVER_NAME);

	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id daqdrv_of_match[] = {
	{ .compatible = "stasbucik,daqdrv", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, daqdrv_of_match);
#else
# define daqdrv_of_match
#endif


static struct platform_driver daqdrv_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= daqdrv_of_match,
	},
	.probe		= daqdrv_probe,
	.remove		= daqdrv_remove,
};

static int __init daqdrv_init(void)
{
	printk("<1>DAQ driver loaded.\n");
	return platform_driver_register(&daqdrv_driver);
}


static void __exit daqdrv_exit(void)
{
	platform_driver_unregister(&daqdrv_driver);
	printk(KERN_ALERT "DAQ driver exited.\n");
}

module_init(daqdrv_init);
module_exit(daqdrv_exit);
